import type { JsonObject } from './json';
import type { EntityId } from './types';

export type DiagnosticSeverity = 'error' | 'info' | 'warning';

export type DiagnosticCode =
  | 'appearance.variant.unresolved'
  | 'command.duplicate-target'
  | 'command.immutable-id'
  | 'command.invalid-clear'
  | 'command.invalid-interval'
  | 'command.invalid-payload'
  | 'command.missing-target'
  | 'command.strict-reference'
  | 'command.unsupported-schedule'
  | 'command.unsupported-target'
  | 'command.unknown-type'
  | 'document.invalid-collection'
  | 'document.invalid-root'
  | 'dependency.cycle'
  | 'dependency.duplicate'
  | 'dependency.working-lag'
  | 'history.stale-outcome'
  | 'layout.invalid-interval'
  | 'layout.missing-schedule'
  | 'layout.missing-segment'
  | 'layout.missing-task'
  | 'layout.non-finite-interval'
  | 'patch.duplicate-target'
  | 'patch.invalid-index'
  | 'patch.invalid-operation'
  | 'patch.invalid-shape'
  | 'patch.invalid-target'
  | 'patch.invalid-value'
  | 'patch.invalid-version'
  | 'patch.missing-target'
  | 'presentation.all-day-date-unavailable'
  | 'presentation.milestone-interval'
  | 'record.duplicate-assignment'
  | 'record.duplicate-dependency'
  | 'record.duplicate-lane'
  | 'record.duplicate-placement'
  | 'record.duplicate-resource'
  | 'record.duplicate-segment'
  | 'record.duplicate-task'
  | 'record.invalid-assignment'
  | 'record.invalid-dependency'
  | 'record.invalid-lane'
  | 'record.invalid-placement'
  | 'record.invalid-resource'
  | 'record.invalid-segment'
  | 'record.invalid-task'
  | 'reference.assignment-resource'
  | 'reference.assignment-task'
  | 'reference.dependency-source'
  | 'reference.dependency-self'
  | 'reference.dependency-target'
  | 'reference.lane-parent'
  | 'reference.lane-resource'
  | 'reference.placement-assignment'
  | 'reference.placement-lane'
  | 'reference.placement-segment'
  | 'reference.placement-task'
  | 'reference.resource-parent'
  | 'reference.task-parent'
  | 'reference.task-parent-cycle'
  | 'reference.task-parent-kind'
  | 'reference.task-parent-self'
  | 'runtime.aborted'
  | 'runtime.callback-threw'
  | 'runtime.controlled-proposal-diverged'
  | 'runtime.disposed'
  | 'runtime.history-empty'
  | 'runtime.history-rejected'
  | 'runtime.internal-error'
  | 'runtime.interceptor-threw'
  | 'runtime.invalid-interceptor-result'
  | 'runtime.pending-proposal'
  | 'runtime.read-only'
  | 'runtime.stale-base'
  | 'render.invalid-task-interval'
  | 'render.missing-task-schedule'
  | 'render.non-finite-task-time'
  | 'schema.invalid-version'
  | 'schema.migration-missing'
  | 'schema.migration-result'
  | 'schema.missing-version'
  | 'schema.unsupported-version'
  | 'time-scale.invalid-bounds'
  | 'value.invalid-all-day-date'
  | 'value.invalid-enum'
  | 'value.invalid-id'
  | 'value.invalid-instant'
  | 'value.invalid-json'
  | 'value.invalid-number'
  | 'value.invalid-string'
  | 'value.unknown-property'
  | 'view.assignment-resource'
  | 'view.assignment-task'
  | 'view.duplicate-lane-key'
  | 'view.duplicate-placement-key'
  | 'view.duplicate-source-id'
  | 'view.invalid-definition'
  | 'view.missing-assignment'
  | 'view.missing-lane'
  | 'view.missing-segment'
  | 'view.missing-task'
  | 'view.project-filter'
  | 'view.project-query'
  | 'view.project-sort';

export interface Diagnostic {
  readonly code: DiagnosticCode;
  readonly severity: DiagnosticSeverity;
  readonly message: string;
  readonly entityIds?: readonly EntityId[];
  readonly path?: string;
  readonly details?: JsonObject;
}
